export const actionTypes = {
  SET_TRADES: 'SET_TRADES',
  SET_COINS: 'SET_COINS',
  SET_ORDERBOOK: 'SET_ORDERBOOK',
  SET_CANDLESTICK: 'SET_CANDLESTICK',
  SET_COINS_SORT: 'SET_COINS_SORT',
  SET_RISK: 'SET_RISK',
  SET_ASSET: 'SET_ASSET',
};
